### ISSUE TITLE
Same reminder is picked multiple times in a row

### ISSUE THREAD

**Issue by zykure** [kmac/mindfulnotifier#24]
Hello there! I recently found this app and it's just great, exactly what I was looking for. Thanks for putting it together!

Now I noticed that sometimes, the same reminder is shown twice or even thrice in a row; i.e. the randomly picked one happens to be the same as the one that was just shown. I suggest to add a check for that, and just pick another reminder in this case.

**Comment by wolftune** [comment]
This is why "shuffle" feature in such things as song playlists are *non* random. They shuffle things into some order but do it's designed for a degree of mixing up.

I'd actually love to get a shuffle feature that purposely mixed up reminders by tag (so if I have 4 tags across many reminders, I get a mix of reminders from the 4 categories)

**Comment by kmac** [comment]
Thanks for the nice feedback @zykure. The app is currently doing a randomized list shuffle. But I have been meaning to use a proper random number generator, so I will switch it to get a random index instead. If I reuse the random number generator it may change things a bit. For the record, I don't see very many repeats, not more than one would expect with a randomized selector.

So as wolftune says, you will still occasionally see a repeat of a reminder. If you happen to add more reminders then the odds of this happening decrease as more reminders are added.

Also, since I recently added this feature: sometimes I will disable a reminder if I don't want to see it for a while.

**Comment by kmac** [comment]
I tweaked this in 1.0.15. It should be as random as I can make it.
