### ISSUE TITLE
Play bell as media, not notification

### ISSUE THREAD

**Issue by lkblkb** [kmac/mindfulnotifier#31]
Super app!

My phone lives in vibrate mode because I have a lot of notifications and it would be super annoying to have these ringing constantly. 

However this also means the app does not work for me, since the bells are notifications and not media. 

This may be an unusual case but it would be awesome to have the option to play the bell as media :)

**Comment by kmac** [comment]
Thanks for the feedback - much appreciated! Yes, I've been meaning to provide this as an option.
I'll try to do something for it when I add the separate in-app volume control. It may be a few weeks however - I'm quite busy with a new job at the moment.

**Comment by lkblkb** [comment]
Awesome, thank you! No hurry.

**Comment by march42** [comment]
This would be a great feature, thanks for suggesting it. Thanks for this App and your efforts on this topic.

**Comment by kmac** [comment]
Added in 1.0.16. The preference is in the 'Sound' menu, along with the bell configurations (I renamed the 'Bell' menu to 'Sound' with this update). You can select between three channels: notification, media, and alarm.

**Comment by lkblkb** [comment]
Thanks you! I updated but the audio does not play via media it seems. Audio channel is set to media. But I need to turn off the phone's vibrate or silent mode to get the bell to play. Media audio for other apps works fine while the phone is on vibrate.

**Comment by kmac** [comment]
I think you're probably looking for Issue #22 - which I'm having some difficulty figuring out how to implement. I'm using an audio library that mutes the sound as per the android system, which is why no audio is playing when you have you're phone muted.

Further complicating things is that Android is changing all of this behaviour as the versions update. Which version of Android are you running?

Can I suggest trying the 'alarm' channel? Alarms are often treated as a higher priority. Again, it depends on your Android version. 

The other thing you could try for the media channel is to manually set the volume on your notification channel to 0 (rather than mute your phone), and set the media volume to whatever you like. There shouldn't be anything coming through the media channel other than if you are playing media. 

Hope this helps.

**Comment by lkblkb** [comment]
@kmac just want to say thank you for this, it's working now and I really appreciate this project! 🙏
