### ISSUE TITLE
Background service disabled on app reopen

### ISSUE THREAD

**Issue by pepedelosbosques** [kmac/mindfulnotifier#35]
When I enable the service, notification is triggered and new notification is setup. (this is as expected)

As soon as I close the app and open it again, the service is disable and the notification disapears. (this is not expected)

**Comment by kmac** [comment]
Hmm, yes I can reproduce this if I try as well. 

This seems to happen is you do the following:

- Enable the service
- Use the back button to exit
- Then use the 'Mindful Notifier is enabled' notification to launch the app. Actually, no, I've also seen it when launching the app via the main app launch icon as well.

It seems also like it's some sort of race condition because it happens on my phone but not in the emulator. And it doesn't happen on my phone every time.

I _don't_ think it's an issue once the app has fired it's first alarm-based notification. That is, it's only an issue when using the back button when first enabled. Please correct me if I'm wrong. I can only make it happen after a disable/enable.

In the meantime, until I fix this, don't use the back button to exit the app, just use the home button.

**Comment by kmac** [comment]
I will try to fix this one up. Unfortunately the threading model in flutter is odd - different threads cannot share memory so I've battled a few issues around sharing state between the UI thread and the alarm/scheduler thread. 

I do tend to avoid exiting the app via the back button though. Like I said, I think once you get the first alarm coming through, then the alarm service has taken over and doesn't need the UI to be running. Until then there does seem to be some state-related issues that still need to be ironed out.

**Comment by kmac** [comment]
I've actually taken a few tries to fix this in my local branches, but so far I haven't had a lot of success. I may end up temporarily disabling the back button until the first notification goes through. Not ready to go that route quite yet though.

**Comment by kmac** [comment]
I was having problems with synchronization between the UI and the alarm service using android SharedPreferences module. I switched things over to flutter Hive to store all the application data. It should be properly migrated after upgrade. But it's always a good idea to backup your reminders via 'Export Reminders'. 
I also added a new datastore field, nextAlarm, which is used to better track the state when the UI is killed via the back button.
