### ISSUE TITLE
Add ability to enter specific hours for alerts.

### ISSUE THREAD

**Issue by CapSel** [kmac/mindfulnotifier#8]
...So that I can exclude time of meatings in day job...
or at least a way for setting up alert every 45 minutes...
or perhaps add those alerts to calendar

**Comment by kmac** [comment]
FYI I plan to keep this app fairly simple - I don't see ever adding more advanced calendar-type functionality.

One think I would suggest as a workaround is putting your phone on mute, vibrate, or DND during meetings. The app will respect the phone mute/vibrate settings as well as the settings in the app. The phone settings have priority, so if the phone is in mute then the bell won't ring.

I didn't add an option to schedule for 45 minutes because that's not aligned to the top of the hour - I could add that option back in but it might be somewhat confusing for people(I think they generally expect bells to align with the top of the hour)  - Note that you could always use random mode and set both max/min to 45 mins if you don't care about hour alignment.

**Comment by CapSel** [comment]
OK. Thank you for your explanation and suggestions. This solves my problem.
