### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by cboneth** [kmac/mindfulnotifier#9]
The dominant color in the dark theme obscurs the white font rendering it almost invisible.

**Comment by kmac** [comment]
I'm not exactly sure what you mean by this... the only issue I'm aware of with the dark theme is the buttons (greenish background/white text) for the add/edit reminders dialog. I just haven't got around to fixing that. Is there something else you are having issues with besides that? thanks for the feedback.

**Comment by cboneth** [comment]
Yes, it's the button, and the add/edit reminder window in general, ie. dark
font on greyish background. I know, it's just aesthetics.

The app and the idea itself is very good.

**Comment by kmac** [comment]
Thanks for the feedback. It's interesting because on my phone and the emulator (Pixel 3a) the dark mode text for the main reminder is quite visible. However, I do have it set to a grey tone. I will lighten up the grey tone in the next release. 
I'm also fixing up the dialog buttons.
I'm testing out a few changes and will be pushing a new release sometime in the next few days.

**Comment by cboneth** [comment]
I understand it can be quite painful to achieve something universal when
there's so many mobile variations. Anyways, good luck. I made a screenshot
to reflect the issue.

**Comment by kmac** [comment]
I can't see the screenshot, if you can drop it into a comment I'd appreciate it!

**Comment by cboneth** [comment]
Sorry, it should be up now. I edited the previous comment.

**Comment by kmac** [comment]
Thanks for clarifying this. I thought you meant that the text on the main window was illegible on the main UI. Now I see, and mine is similar.
I'll have this fixed in the next release.

**Comment by kmac** [comment]
Fixed in 1.0.10. Thanks for the input, and please let me know if I missed anything.
